### ISSUE TITLE
Clarification on the `DialogContent`

### ISSUE THREAD

**Issue by kittaakos** [GEGlobalResearch/DARPA-ASKE-TA1#36]
@crapo, I have the following model. Let's assume, the imported `Model.sadl` exists and valid.
```
uri "http://darpa/aske/ge/ta1/testdlg" alias tdlg.

import "http://sadl.org/Model.sadl".

MyHulk is a Mass with ^value 280, with unit "lbs".

Ask unit of MyHulk? CM: "lbs".
 
What is acceleration? CM: acceleration describes Mass with values of type Acceleration.
```

I set a breakpoint to the `AnswerCurationManager.processConversation(Resource, OntModel, String)` and when I open the model in the editor, I can see the `DialogContent` initialized with this state:

```
Dialog content:
USER: MyHulk is a Mass with ^value 280, with unit "lbs".
USER: Ask unit of MyHulk?
USER: CM: "lbs".
USER: What is acceleration?
USER: CM: acceleration describes Mass with values of type Acceleration.
```

Question: can you please tell me why can I see `USER: CM: "lbs".` and `USER: CM: acceleration describes Mass with values of type Acceleration.` in the dialog content? They were already in the file, and not the user added them but CM.

Thank you!

**Comment by crapo** [comment]
Surely. The conversation (dialog content) is a reflection of what is in the Dialog editor window. Once a question has been answered, e.g., question: "What is acceleration?", answer: "CM: acceleration describes Mass with values of type Acceleration.", we do not want to answer it again. If the answers weren't there we'd have no way of knowing that we shouldn't just keep answering it over and over and adding the answers to the Dialog window ad nauseam. 
We have not yet dealt with the possibility that the question has been edited, but since we keep a map of questions and answers, I believe that we have the groundwork in place to address that issue in the future.

**Comment by kittaakos** [comment]
> If the answers weren't there we'd have no way of knowing that we shouldn't just keep answering

It makes sense. Thank you!
