### ISSUE TITLE
Creation of DialogAnswerProviderConsoleForTest and AnswerCurationManager for JUnit test

### ISSUE THREAD

**Issue by crapo** [GEGlobalResearch/DARPA-ASKE-TA1#39]
Now that the DialogAnswerProvider is created in a robust manner from the IDE, the JUnit test cases are finding no AnswerCurationManager from the JenaBasedDialogModelProcessor. Is a reasonable solution to have the AbstractDialogText initialize method create an IDialogAnswerProvider (a DialogAnswerProviderConsoleForTest and an AnswerCurationManger, much as DialogAnswerProviders.register calls the IDialogAnswerProvider.configure, which creates the AnswerCurationManager?

**Comment by kittaakos** [comment]
@crapo, this is due to these changes:
 - https://github.com/GEGlobalResearch/DARPA-ASKE-TA1/commit/e3a8c7459f210b9a386609a2e3b350291f850ca5#diff-42ed585e1554ca3f8566a083806ed273L764

 - https://github.com/GEGlobalResearch/DARPA-ASKE-TA1/commit/e3a8c7459f210b9a386609a2e3b350291f850ca5#diff-e7574beed848891dd5ff1389226b9b7fR116

Why was the removal? I am going to restore it. Otherwise, it can't work.

**Comment by crapo** [comment]
It was pretty painful to integrate all of the changes that I had made on master with the core-answer branch, so I may have messed it up. Not sure precisely what was deleted that causes the problem, but when you restore I can see.
